site_name: ECE Projekt - 4D Game
nav:
  - Home:
      - Instructions: index.md
      - Assembly: assembly.md
      - Documentation: documentation.md
  - Coding Style:
      - C++: coding-style/cpp.md
      - Python: coding-style/python.md
      - GIT: coding-style/git.md
  - Game Code:
      - Controller: https://4d-game.github.io/Controller/
      - Gamecontrol: https://4d-game.github.io/Gamecontrol/
  - SDK:
      - Overview: sdk/index.md
      - Game SDK: https://4d-game.github.io/Controller/sdk
      - Gamecontrol SDK: https://4d-game.github.io/Gamecontrol/sdk/

repo_url: https://github.com/4D-Game/4D-Game.github.io
repo_name: '4D-Game/Dokumentation'

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    # - scheme: default
    #   primary: light blue
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    - scheme: slate
      primary: light blue
      # toggle:
      #   icon: material/toggle-switch
      #   name: Switch to light mode

plugins:
  - search
  - mermaid2:
      arguments:
        theme: 'dark'

markdown_extensions:
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
