site_name: ECE Projekt - 4D Game
nav:
  - Home: index.md
  - Coding Style:
      - C++: coding-style/cpp.md
      - Python: coding-style/python.md
      - GIT: coding-style/git.md
  - Code References:
      - Streamer: https://4d-game.github.io/Streamer/
      - Controller: https://4d-game.github.io/Controller/
      - Watcherstream: https://4d-game.github.io/Watcherstream/

repo_url: https://github.com/4D-Game/4D-Game.github.io

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
